---
language: node_js
node_js:
  - 'lts/*'
sudo: false

before_install:
  - npm i -g npm@latest

install:
  - npm ci

before_script:
  - bin/fetch-configlet

script:
  - bin/configlet lint .
  - npx @babel/node scripts/ci
