# This workflow will do a clean install of node dependencies and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: javascript / ci

on: pull_request

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js LTS (12.x)
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci precheck (stub files, config integrity)
        run: npx babel-node scripts/ci-check

  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci (runs tests)
        run: npx babel-node scripts/pr
