# This workflow will check stub files, integrity, and potentially other checks

name: javascript ci

on:
  push:
    branches: [master]

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install project dependencies
        run: npm ci

      - name: Run exercism/javascript ci precheck (checks config, lint code, and runs tests) for all exercises
        run: npx babel-node scripts/ci-check
