# This workflow will do a fetch the latest configlet binary and lint this repository.

name: exercism/configlet lint

on: [push, pull_request]

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@master

      - name: Configlet Linter
        run: configlet lint .
