name: javascript / format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
      - name: Use Node.js LTS (18.x)
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: '18'
      - name: Install project development dependencies
        run: npm i
      - name: 'Verify formatting of all files'
        run: ./bin/check-formatting.sh
